# Generated by Django 6.1 on 2026-10-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='label',
            new_name='labels',
        ),
    ]
